import type { Contact } from "../types";

export const mockContacts: Contact[] = [
  {
    id: "c1",
    name: "Marc Leblanc",
    firstName: "Marc",
    lastName: "Leblanc",
    title: "Head of Sales",
    company: "Allianz France",
    sector: "Assurance",
    linkedinUrl: "https://linkedin.com/in/marc-leblanc",
    email: "marc.leblanc@allianz.fr",
    relationshipType: "alumni",
    tags: ["decision-maker", "high-priority", "IA"],
    status: "to-relaunch",
    relationshipScore: 72,
    lastInteractionAt: "2025-09-15T10:00:00Z",
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "c2",
    name: "Sarah Dupont",
    firstName: "Sarah",
    lastName: "Dupont",
    title: "CTO",
    company: "TechCorp",
    sector: "Tech / SaaS",
    linkedinUrl: "https://linkedin.com/in/sarah-dupont",
    email: "sarah.dupont@techcorp.io",
    relationshipType: "former-colleague",
    tags: ["decision-maker", "scale-up", "engineering"],
    status: "to-relaunch",
    relationshipScore: 65,
    lastInteractionAt: "2025-12-01T14:30:00Z",
    createdAt: "2023-03-15T00:00:00Z",
  },
  {
    id: "c3",
    name: "Thomas Moreau",
    firstName: "Thomas",
    lastName: "Moreau",
    title: "Directeur Transformation Digitale",
    company: "BNP Paribas",
    sector: "Banque",
    linkedinUrl: "https://linkedin.com/in/thomas-moreau",
    relationshipType: "client",
    tags: ["decision-maker", "transformation", "grand-compte"],
    status: "relaunched",
    relationshipScore: 85,
    lastInteractionAt: "2026-02-20T09:00:00Z",
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "c4",
    name: "Julie Martin",
    firstName: "Julie",
    lastName: "Martin",
    title: "VP People & Culture",
    company: "Doctolib",
    sector: "HealthTech",
    linkedinUrl: "https://linkedin.com/in/julie-martin",
    email: "julie.martin@doctolib.com",
    relationshipType: "alumni",
    tags: ["HR", "scale-up", "culture"],
    status: "to-relaunch",
    relationshipScore: 45,
    lastInteractionAt: "2025-06-20T16:00:00Z",
    createdAt: "2023-09-01T00:00:00Z",
  },
  {
    id: "c5",
    name: "Alexandre Petit",
    firstName: "Alexandre",
    lastName: "Petit",
    title: "Partner",
    company: "McKinsey & Company",
    sector: "Conseil",
    linkedinUrl: "https://linkedin.com/in/alexandre-petit",
    relationshipType: "former-colleague",
    tags: ["senior", "stratégie", "consulting"],
    status: "up-to-date",
    relationshipScore: 90,
    lastInteractionAt: "2026-03-05T11:00:00Z",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: "c6",
    name: "Camille Roux",
    firstName: "Camille",
    lastName: "Roux",
    title: "Head of Data & AI",
    company: "Société Générale",
    sector: "Banque",
    linkedinUrl: "https://linkedin.com/in/camille-roux",
    email: "camille.roux@socgen.com",
    relationshipType: "prospect",
    tags: ["data", "IA", "grand-compte"],
    status: "new",
    relationshipScore: 30,
    lastInteractionAt: null,
    createdAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "c7",
    name: "Nicolas Bernard",
    firstName: "Nicolas",
    lastName: "Bernard",
    title: "CEO & Co-founder",
    company: "DataWave",
    sector: "Tech / SaaS",
    linkedinUrl: "https://linkedin.com/in/nicolas-bernard",
    email: "nicolas@datawave.ai",
    relationshipType: "alumni",
    tags: ["entrepreneur", "IA", "startup"],
    status: "to-relaunch",
    relationshipScore: 55,
    lastInteractionAt: "2025-10-12T08:00:00Z",
    createdAt: "2023-06-01T00:00:00Z",
  },
  {
    id: "c8",
    name: "Émilie Fournier",
    firstName: "Émilie",
    lastName: "Fournier",
    title: "Directrice Marketing",
    company: "L'Oréal",
    sector: "Luxe / Cosmétiques",
    linkedinUrl: "https://linkedin.com/in/emilie-fournier",
    relationshipType: "client",
    tags: ["marketing", "digital", "grand-compte"],
    status: "relaunched",
    relationshipScore: 78,
    lastInteractionAt: "2026-01-15T14:00:00Z",
    createdAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "c9",
    name: "Pierre Leclerc",
    firstName: "Pierre",
    lastName: "Leclerc",
    title: "DSI",
    company: "AXA France",
    sector: "Assurance",
    linkedinUrl: "https://linkedin.com/in/pierre-leclerc",
    relationshipType: "prospect",
    tags: ["DSI", "cloud", "cyber"],
    status: "to-relaunch",
    relationshipScore: 40,
    lastInteractionAt: "2025-11-01T10:00:00Z",
    createdAt: "2025-02-01T00:00:00Z",
  },
  {
    id: "c10",
    name: "Laura Chen",
    firstName: "Laura",
    lastName: "Chen",
    title: "Senior Manager — Digital Advisory",
    company: "Capgemini",
    sector: "Conseil",
    linkedinUrl: "https://linkedin.com/in/laura-chen",
    email: "laura.chen@capgemini.com",
    relationshipType: "former-colleague",
    tags: ["conseil", "digital", "advisory"],
    status: "up-to-date",
    relationshipScore: 82,
    lastInteractionAt: "2026-02-28T16:30:00Z",
    createdAt: "2022-09-01T00:00:00Z",
  },
  {
    id: "c11",
    name: "Maxime Girard",
    firstName: "Maxime",
    lastName: "Girard",
    title: "Chief Revenue Officer",
    company: "Qonto",
    sector: "FinTech",
    linkedinUrl: "https://linkedin.com/in/maxime-girard",
    relationshipType: "alumni",
    tags: ["revenue", "fintech", "scale-up"],
    status: "to-relaunch",
    relationshipScore: 50,
    lastInteractionAt: "2025-08-10T09:00:00Z",
    createdAt: "2023-11-01T00:00:00Z",
  },
  {
    id: "c12",
    name: "Sophie Durand",
    firstName: "Sophie",
    lastName: "Durand",
    title: "Responsable Innovation",
    company: "SNCF",
    sector: "Transport / Mobilité",
    linkedinUrl: "https://linkedin.com/in/sophie-durand",
    email: "sophie.durand@sncf.fr",
    relationshipType: "partner",
    tags: ["innovation", "mobilité", "public"],
    status: "relaunched",
    relationshipScore: 68,
    lastInteractionAt: "2026-02-10T11:00:00Z",
    createdAt: "2024-08-01T00:00:00Z",
  },
];
