import type { IntelItem } from "../types";

export const mockIntelItems: IntelItem[] = [
  // Marc Leblanc / Allianz France (c1)
  {
    id: "i1",
    contactId: "c1",
    company: "Allianz France",
    title: "Allianz annonce un partenariat stratégique avec Salesforce pour l'IA commerciale",
    url: "https://lesechos.fr/allianz-salesforce-ia-2026",
    source: "Les Échos",
    date: "2026-02-15",
    summary: "Allianz France et Salesforce s'associent pour déployer une solution d'IA générative au sein des équipes commerciales. L'objectif : automatiser 40% des tâches de reporting et personnaliser les interactions clients.",
    tags: ["partenariat", "IA", "Salesforce", "commercial"],
    score: 0.95,
    type: "partnership",
  },
  {
    id: "i2",
    contactId: "c1",
    company: "Allianz France",
    title: "Marc Leblanc nommé Head of Sales chez Allianz France",
    url: "https://linkedin.com/posts/allianz-marc-promotion",
    source: "LinkedIn",
    date: "2026-01-20",
    summary: "Marc Leblanc prend la tête de la direction commerciale d'Allianz France après 3 ans en tant que Directeur Régional. Sa mission : accélérer la digitalisation du parcours de vente.",
    tags: ["promotion", "nomination", "commercial"],
    score: 0.98,
    type: "job-change",
  },
  {
    id: "i3",
    contactId: "c1",
    company: "Allianz France",
    title: "Allianz lance un nouveau produit d'assurance cyber pour les PME",
    url: "https://argusdelassurance.com/allianz-cyber-pme",
    source: "L'Argus de l'Assurance",
    date: "2026-03-01",
    summary: "Face à la hausse des cyberattaques (+35% en 2025), Allianz dévoile une offre dédiée aux PME combinant assurance, prévention et accompagnement post-incident.",
    tags: ["cyber", "PME", "produit", "innovation"],
    score: 0.82,
    type: "product-launch",
  },

  // Sarah Dupont / TechCorp (c2)
  {
    id: "i4",
    contactId: "c2",
    company: "TechCorp",
    title: "TechCorp lève 45M€ en Série C pour accélérer son expansion européenne",
    url: "https://techcrunch.com/techcorp-serie-c-2026",
    source: "TechCrunch",
    date: "2026-02-28",
    summary: "La scale-up française TechCorp boucle un tour de table de 45 millions d'euros mené par Accel et Eurazeo. L'objectif : tripler les effectifs R&D et ouvrir des bureaux à Berlin et Londres.",
    tags: ["levée de fonds", "série C", "expansion", "R&D"],
    score: 0.96,
    type: "funding",
  },
  {
    id: "i5",
    contactId: "c2",
    company: "TechCorp",
    title: "TechCorp lance une plateforme d'IA pour l'automatisation des workflows",
    url: "https://journaldunet.com/techcorp-ia-workflow",
    source: "Journal du Net",
    date: "2026-03-05",
    summary: "TechCorp dévoile AutoFlow AI, une plateforme no-code permettant aux entreprises d'automatiser leurs processus métier grâce à l'IA générative. Premier client : un grand groupe bancaire français.",
    tags: ["produit", "IA", "automatisation", "no-code"],
    score: 0.91,
    type: "product-launch",
  },
  {
    id: "i6",
    contactId: "c2",
    company: "TechCorp",
    title: "Sarah Dupont parmi les '50 Women in Tech France 2026'",
    url: "https://usinenouvelle.com/women-in-tech-2026",
    source: "L'Usine Nouvelle",
    date: "2026-02-10",
    summary: "La CTO de TechCorp figure dans le classement annuel des femmes les plus influentes de la tech française, saluée pour sa vision de l'IA responsable.",
    tags: ["reconnaissance", "leadership", "diversité"],
    score: 0.88,
    type: "news",
  },

  // Thomas Moreau / BNP Paribas (c3)
  {
    id: "i7",
    contactId: "c3",
    company: "BNP Paribas",
    title: "BNP Paribas investit 500M€ dans sa transformation digitale 2026-2028",
    url: "https://lesechos.fr/bnp-transformation-digitale-2026",
    source: "Les Échos",
    date: "2026-02-22",
    summary: "Le groupe bancaire annonce un plan massif de transformation digitale sur 3 ans, axé sur l'IA, le cloud et la modernisation des systèmes legacy. 2000 recrutements prévus dans le digital.",
    tags: ["transformation", "investissement", "digital", "cloud"],
    score: 0.97,
    type: "news",
  },
  {
    id: "i8",
    contactId: "c3",
    company: "BNP Paribas",
    title: "BNP Paribas signe avec Google Cloud pour migrer ses infrastructures",
    url: "https://silicon.fr/bnp-google-cloud-2026",
    source: "Silicon",
    date: "2026-03-08",
    summary: "BNP Paribas choisit Google Cloud comme partenaire stratégique pour la migration de 60% de ses workloads. Un contrat estimé à 200M€ sur 5 ans.",
    tags: ["cloud", "Google", "migration", "infrastructure"],
    score: 0.93,
    type: "partnership",
  },
  {
    id: "i9",
    contactId: "c3",
    company: "BNP Paribas",
    title: "BNP Paribas lance un lab IA dédié à la conformité réglementaire",
    url: "https://banque-finance.fr/bnp-lab-ia-conformite",
    source: "Banque & Finance",
    date: "2026-02-05",
    summary: "Le lab, basé à Paris, développera des solutions d'IA pour automatiser les contrôles KYC/AML et réduire les coûts de conformité de 30% d'ici 2028.",
    tags: ["IA", "conformité", "RegTech", "innovation"],
    score: 0.85,
    type: "product-launch",
  },

  // Camille Roux / Société Générale (c6)
  {
    id: "i10",
    contactId: "c6",
    company: "Société Générale",
    title: "Société Générale recrute 300 experts Data & IA en 2026",
    url: "https://lefigaro.fr/socgen-recrutement-data-2026",
    source: "Le Figaro",
    date: "2026-03-02",
    summary: "La banque accélère sa stratégie data avec un plan de recrutement massif : 300 profils data engineers, data scientists et ML engineers seront embauchés cette année.",
    tags: ["recrutement", "data", "IA", "stratégie"],
    score: 0.92,
    type: "news",
  },
  {
    id: "i11",
    contactId: "c6",
    company: "Société Générale",
    title: "Société Générale dévoile son assistant IA pour les conseillers bancaires",
    url: "https://banque-magazine.fr/socgen-assistant-ia",
    source: "Banque Magazine",
    date: "2026-02-18",
    summary: "L'assistant 'SG Copilot' aide les conseillers à préparer leurs rendez-vous clients en synthétisant automatiquement l'historique des interactions et les produits adaptés.",
    tags: ["IA", "assistant", "conseiller", "produit"],
    score: 0.89,
    type: "product-launch",
  },
  {
    id: "i12",
    contactId: "c6",
    company: "Société Générale",
    title: "Camille Roux intervient au sommet AI Paris 2026",
    url: "https://ai-paris.com/speakers/camille-roux",
    source: "AI Paris",
    date: "2026-03-12",
    summary: "La Head of Data & AI de la Société Générale présentera la stratégie IA du groupe et les cas d'usage en production lors du plus grand événement IA français.",
    tags: ["conférence", "leadership", "IA", "stratégie"],
    score: 0.86,
    type: "news",
  },

  // Nicolas Bernard / DataWave (c7)
  {
    id: "i13",
    contactId: "c7",
    company: "DataWave",
    title: "DataWave lève 12M€ pour son moteur de recommandation IA B2B",
    url: "https://maddyness.com/datawave-levee-2026",
    source: "Maddyness",
    date: "2026-02-25",
    summary: "La startup fondée par Nicolas Bernard boucle sa Série A auprès de Partech et Bpifrance. DataWave ambitionne de devenir le leader européen de la recommandation IA pour le e-commerce B2B.",
    tags: ["levée de fonds", "série A", "IA", "B2B"],
    score: 0.94,
    type: "funding",
  },
  {
    id: "i14",
    contactId: "c7",
    company: "DataWave",
    title: "DataWave signe un partenariat avec Shopify pour l'Europe",
    url: "https://frenchweb.fr/datawave-shopify-europe",
    source: "FrenchWeb",
    date: "2026-03-10",
    summary: "DataWave devient partenaire officiel de Shopify pour le marché européen, intégrant son moteur de recommandation IA directement dans la marketplace Shopify.",
    tags: ["partenariat", "Shopify", "e-commerce", "Europe"],
    score: 0.90,
    type: "partnership",
  },
  {
    id: "i15",
    contactId: "c7",
    company: "DataWave",
    title: "Nicolas Bernard nommé dans le classement 'Entrepreneurs to Watch' de Forbes France",
    url: "https://forbes.fr/entrepreneurs-2026",
    source: "Forbes France",
    date: "2026-01-30",
    summary: "Le CEO de DataWave figure parmi les 30 entrepreneurs français à suivre en 2026, salué pour l'innovation technologique et la croissance rapide de sa startup.",
    tags: ["reconnaissance", "entrepreneur", "classement"],
    score: 0.87,
    type: "news",
  },

  // Julie Martin / Doctolib (c4)
  {
    id: "i16",
    contactId: "c4",
    company: "Doctolib",
    title: "Doctolib franchit le cap des 80 millions d'utilisateurs en Europe",
    url: "https://challenges.fr/doctolib-80m-utilisateurs",
    source: "Challenges",
    date: "2026-02-12",
    summary: "La licorne française de la e-santé annonce avoir dépassé les 80 millions d'utilisateurs actifs, portée par son expansion en Italie et aux Pays-Bas.",
    tags: ["croissance", "expansion", "e-santé"],
    score: 0.83,
    type: "news",
  },
  {
    id: "i17",
    contactId: "c4",
    company: "Doctolib",
    title: "Doctolib lance un programme de bien-être au travail salué par les RH",
    url: "https://hbrfrance.fr/doctolib-bien-etre-travail",
    source: "HBR France",
    date: "2026-03-03",
    summary: "Le programme 'Care First' de Doctolib, piloté par Julie Martin, est cité en exemple de politique RH innovante combinant flexibilité, santé mentale et performance.",
    tags: ["RH", "bien-être", "culture", "innovation"],
    score: 0.91,
    type: "news",
  },

  // Maxime Girard / Qonto (c11)
  {
    id: "i18",
    contactId: "c11",
    company: "Qonto",
    title: "Qonto atteint la rentabilité et prépare son entrée en bourse",
    url: "https://lesechos.fr/qonto-rentabilite-ipo-2026",
    source: "Les Échos",
    date: "2026-03-07",
    summary: "La néobanque française pour les PME et indépendants annonce avoir atteint la rentabilité au Q4 2025. Une introduction en bourse est envisagée pour fin 2026.",
    tags: ["rentabilité", "IPO", "fintech", "croissance"],
    score: 0.95,
    type: "news",
  },
  {
    id: "i19",
    contactId: "c11",
    company: "Qonto",
    title: "Qonto lance une offre de crédit IA pour les TPE/PME",
    url: "https://journaldunet.com/qonto-credit-ia",
    source: "Journal du Net",
    date: "2026-02-20",
    summary: "Qonto dévoile un produit de crédit instantané utilisant l'IA pour évaluer la solvabilité en temps réel, réduisant le délai d'octroi de 5 jours à 5 minutes.",
    tags: ["crédit", "IA", "produit", "PME"],
    score: 0.88,
    type: "product-launch",
  },

  // Sophie Durand / SNCF (c12)
  {
    id: "i20",
    contactId: "c12",
    company: "SNCF",
    title: "La SNCF déploie l'IA pour optimiser la maintenance prédictive de ses trains",
    url: "https://usinenouvelle.com/sncf-ia-maintenance-2026",
    source: "L'Usine Nouvelle",
    date: "2026-02-08",
    summary: "Le programme piloté par la direction Innovation permet de prédire les pannes 72h à l'avance, réduisant les retards liés à la maintenance de 25%.",
    tags: ["IA", "maintenance", "innovation", "prédictif"],
    score: 0.87,
    type: "product-launch",
  },
  {
    id: "i21",
    contactId: "c12",
    company: "SNCF",
    title: "SNCF et Alstom signent un accord pour les trains autonomes à l'horizon 2030",
    url: "https://mobilicites.com/sncf-alstom-trains-autonomes",
    source: "Mobilicités",
    date: "2026-03-11",
    summary: "Un partenariat stratégique entre la SNCF et Alstom vise à développer les premiers trains régionaux autonomes en France, avec des tests prévus dès 2027.",
    tags: ["partenariat", "autonome", "innovation", "Alstom"],
    score: 0.84,
    type: "partnership",
  },
];
