import type { MarketTrend } from "../types";

export const mockMarketTrends: MarketTrend[] = [
  {
    id: "t1",
    sector: "Tech / SaaS",
    title: "L'IA générative transforme les directions commerciales",
    description: "Les outils d'IA générative (copilots, assistants) sont adoptés par 60% des directions commerciales du CAC40 pour le scoring leads, la personnalisation des offres et l'automatisation du reporting.",
    impactLevel: "high",
    date: "2026-03-10",
    relatedCompanies: ["Allianz France", "TechCorp", "Société Générale"],
  },
  {
    id: "t2",
    sector: "FinTech",
    title: "Vague de consolidation dans la FinTech européenne",
    description: "Après 3 ans de correction, la fintech européenne entre dans une phase de consolidation. Les acteurs rentables comme Qonto attirent les investisseurs tandis que les plus fragiles sont rachetés.",
    impactLevel: "high",
    date: "2026-03-07",
    relatedCompanies: ["Qonto", "BNP Paribas"],
  },
  {
    id: "t3",
    sector: "Assurance",
    title: "Cybersécurité : budgets en hausse de 25% dans le CAC40",
    description: "Face à la multiplication des cyberattaques (+35% en 2025), les grands groupes augmentent massivement leurs budgets sécurité. L'assurance cyber pour les PME explose.",
    impactLevel: "medium",
    date: "2026-02-28",
    relatedCompanies: ["Allianz France", "AXA France"],
  },
  {
    id: "t4",
    sector: "Banque",
    title: "Le cloud souverain devient un critère d'achat clé",
    description: "Les régulateurs européens imposent des exigences croissantes sur la localisation des données. Le cloud souverain n'est plus une option mais une obligation pour les acteurs financiers.",
    impactLevel: "medium",
    date: "2026-02-20",
    relatedCompanies: ["BNP Paribas", "Société Générale"],
  },
  {
    id: "t5",
    sector: "Conseil",
    title: "Les ESN accélèrent sur l'offre consulting IA",
    description: "Capgemini, CGI, Accenture et les cabinets de conseil traditionnels lancent des practices dédiées à l'IA. La demande en conseil IA a triplé en 12 mois.",
    impactLevel: "high",
    date: "2026-03-05",
    relatedCompanies: ["Capgemini", "McKinsey & Company"],
  },
  {
    id: "t6",
    sector: "HealthTech",
    title: "La télémédecine se généralise en Europe",
    description: "Après la pandémie, la télémédecine s'installe durablement dans les pratiques médicales européennes. Les plateformes comme Doctolib étendent leurs services au-delà de la prise de rendez-vous.",
    impactLevel: "medium",
    date: "2026-02-15",
    relatedCompanies: ["Doctolib"],
  },
  {
    id: "t7",
    sector: "Transport / Mobilité",
    title: "La mobilité autonome progresse vers la commercialisation",
    description: "Les premiers tests de navettes et trains autonomes en conditions réelles débutent en Europe. La France se positionne comme pionnière avec le programme SNCF × Alstom.",
    impactLevel: "high",
    date: "2026-03-12",
    relatedCompanies: ["SNCF"],
  },
  {
    id: "t8",
    sector: "Luxe / Cosmétiques",
    title: "L'IA au service de la personnalisation beauté",
    description: "Les marques de luxe et cosmétiques investissent massivement dans l'IA pour personnaliser l'expérience client : diagnostics peau IA, recommandations produits, essayage virtuel.",
    impactLevel: "medium",
    date: "2026-02-25",
    relatedCompanies: ["L'Oréal"],
  },
];
